logging:
  file:
    name: logs/api.log
  level:
    root: info
    org.msa.item: debug
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/msa
    username: root
    password: "!qwer1234"
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
